AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LogS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::AccountId}-logs-bucket'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  LogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LogS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudTrailLogs
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: 's3:PutObject'
            Resource: !Sub '${LogS3Bucket.Arn}/cloudtrail/AWSLogs/${AWS::AccountId}/*'
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
          - Sid: AllowVPCCaptureLogs
            Effect: Allow
            Principal:
              Service: delivery.logs.amazonaws.com
            Action: 's3:PutObject'
            Resource: !Sub '${LogS3Bucket.Arn}/vpc-flow-logs/AWSLogs/${AWS::AccountId}/*'
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
          - Sid: AllowCloudTrailGetBucketACL
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: 's3:GetBucketAcl'
            Resource: !Sub '${LogS3Bucket.Arn}'

  CloudTrailRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: CloudTrailPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                Resource: !Sub '${LogS3Bucket.Arn}/cloudtrail/AWSLogs/${AWS::AccountId}/*'
                Condition:
                  StringEquals:
                    s3:x-amz-acl: bucket-owner-full-control

  VPCFlowLogsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: delivery.logs.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: VPCFlowLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                Resource: !Sub '${LogS3Bucket.Arn}/vpc-flow-logs/AWSLogs/${AWS::AccountId}/*'
                Condition:
                  StringEquals:
                    s3:x-amz-acl: bucket-owner-full-control

  CloudTrailTrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: MyCloudTrail
      S3BucketName: !Ref LogS3Bucket
      S3KeyPrefix: cloudtrail
      IsLogging: true
      IncludeGlobalServiceEvents: true
      ManagementEvents: 'All'
      EventSelectors:
        - ReadWriteType: All
          IncludeManagementEvents: true
          DataResources:
            - Type: AWS::S3::Object
              Values:
                - !Sub 'arn:aws:s3:::${AWS::AccountId}/*'

  VPCFlowLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/vpc-flow-logs/${VPCID}'
      RetentionInDays: 365

  VPCFlowLogsSubscription:
    Type: AWS::EC2::FlowLog
    Properties:
      DeliverLogsPermissionArn: !GetAtt VPCFlowLogsRole.Arn
      LogGroupName: !Ref VPCFlowLogs
      ResourceId: 'vpc-01877e0cdf63832e3'
      ResourceType: VPC
      TrafficType: ALL
      LogDestinationType: s3
      LogDestination: !GetAtt LogS3Bucket.Arn
      LogFormat: '${version} ${account-id} ${interface-id} ${srcaddr} ${dstaddr} ${srcport} ${dstport} ${protocol} ${packets} ${bytes} ${start} ${end} ${action} ${log-status}'
      MaxAggregationInterval: 60

Outputs:
  S3BucketName:
    Description: "The name of the S3 bucket where logs are stored"
    Value: !Ref LogS3Bucket

  CloudTrailName:
    Description: "The name of the CloudTrail trail"
    Value: !Ref CloudTrailTrail

  VPCFlowLogsGroup:
    Description: "The name of the Log Group where VPC Flow Logs are stored"
    Value: !Ref VPCFlowLogs
