AWSTemplateFormatVersion: '2010-09-09'
Description: Enable CloudTrail logging for management and S3 events, and configure VPC Flow Logs, both stored in the same S3 bucket under different folders.

Resources:
  # S3 Bucket for CloudTrail and VPC Flow Logs
  LogS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub cloudtrail-vpc-logs-${AWS::AccountId}-${AWS::Region}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  # IAM Role for CloudTrail
  CloudTrailIAMRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudTrailPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - s3:PutObject
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                Resource: 
                  - !Sub arn:aws:s3:::${LogS3Bucket}/CloudTrailEvents/*
                  - !Sub arn:aws:s3:::${LogS3Bucket}

  # CloudTrail
  CloudTrail:
    Type: AWS::CloudTrail::Trail
    DependsOn: CloudTrailIAMRole
    Properties:
      TrailName: !Sub cloudtrail-${AWS::AccountId}
      S3BucketName: !Ref LogS3Bucket
      S3KeyPrefix: CloudTrailEvents
      IsMultiRegionTrail: true
      IncludeGlobalServiceEvents: true
      EnableLogFileValidation: true
      IsLogging: true
      EventSelectors:
        - DataResources:
            - Type: AWS::S3::Object
              Values:
                - arn:aws:s3:::*
          IncludeManagementEvents: true
          ReadWriteType: All

  # IAM Role for VPC Flow Logs
  VPCFlowLogsIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: vpc-flow-logs.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: VPCFlowLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                Resource: 
                  - !Sub arn:aws:s3:::${LogS3Bucket}/VPCFlowLogs/*
                  - !Sub arn:aws:s3:::${LogS3Bucket}

  # VPC Flow Logs for all VPCs
  VPCFlowLogs:
    Type: AWS::EC2::FlowLog
    Properties:
      DeliverLogsPermissionArn: !GetAtt VPCFlowLogsIAMRole.Arn
      LogDestinationType: s3
      LogDestination: !Sub arn:aws:s3:::${LogS3Bucket}/VPCFlowLogs/
      ResourceId: vpc-01877e0cdf63832e3
      ResourceType: VPC
      TrafficType: ALL
      MaxAggregationInterval: 60
      LogFormat: '${srcaddr} ${dstaddr} ${srcport} ${dstport} ${protocol} ${packets} ${bytes} ${action} ${log-status}'

Outputs:
  S3BucketName:
    Description: "The name of the S3 bucket where logs are stored"
    Value: !Ref LogS3Bucket
  CloudTrailArn:
    Description: "CloudTrail ARN"
    Value: !Ref CloudTrail
  VPCFlowLogsLocation:
    Description: "VPC Flow Logs stored in S3 at this location"
    Value: !Sub arn:aws:s3:::${LogS3Bucket}/VPCFlowLogs/
  CloudTrailEventsLocation:
    Description: "CloudTrail Events stored in S3 at this location"
    Value: !Sub arn:aws:s3:::${LogS3Bucket}/CloudTrailEvents/
