AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template to create an S3 bucket for storing logs, configure CloudTrail to send logs to the bucket,
  and configure VPC Flow Logs for the specified VPC.

Parameters:
  AccountId:
    Type: String
    Description: The AWS Account ID
    Default: !Sub ${AWS::AccountId} # Automatically resolves to the current account ID

  VPCId:
    Type: String
    Description: The ID of the VPC for which VPC Flow Logs will be enabled.
    Default: vpc-01877e0cdf63832e3 # This can remain as it's a string

Resources:
  S3BucketForLogs:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'log-storage-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: "ExpireLogsAfter365Days"
            Status: Enabled
            ExpirationInDays: 365
            Prefix: "logs/"

  S3BucketPolicyForLogs:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3BucketForLogs
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: 's3:PutObject'
            Resource: !Sub 'arn:aws:s3:::log-storage-${AWS::AccountId}/cloudtrail-logs/AWSLogs/${AWS::AccountId}/*'
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
          - Effect: Allow
            Principal:
              Service: vpc-flow-logs.amazonaws.com
            Action: 's3:PutObject'
            Resource: !Sub 'arn:aws:s3:::log-storage-${AWS::AccountId}/vpc-flow-logs/${VPCId}/*'
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AccountId
          - Effect: Allow
            Principal:
              Service: vpc-flow-logs.amazonaws.com
            Action: 's3:Get
