AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template to create an S3 bucket for storing logs,
  configure CloudTrail to send logs to the bucket, and configure VPC Flow Logs
  for the specified VPC to send logs to the same bucket.

Parameters:
  AccountId:
    Type: String
    Description: The AWS Account ID
    Default: !Sub '${AWS::AccountId}'

  VPCId:
    Type: String
    Description: The ID of the VPC for which VPC Flow Logs will be enabled.
    Default: 'vpc-01877e0cdf63832e3' # Update this with your VPC ID

Resources:
  S3BucketForLogs:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'log-storage-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: "ExpireLogsAfter365Days"
            Status: Enabled
            ExpirationInDays: 365
            Prefix: "logs/"

  S3BucketPolicyForLogs:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3BucketForLogs
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: 's3:PutObject'
            Resource: !Sub 'arn:aws:s3:::log-storage-${AWS::AccountId}/cloudtrail-logs/AWSLogs/${AWS::AccountId}/*'
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
          - Effect: Allow
            Principal:
              Service: vpc-flow-logs.amazonaws.com
            Action: 's3:PutObject'
            Resource: !Sub 'arn:aws:s3:::log-storage-${AWS::AccountId}/vpc-flow-logs/${VPCId}/*'
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AccountId
          - Effect: Allow
            Principal:
              Service: vpc-flow-logs.amazonaws.com
            Action: 's3:GetBucketAcl'
            Resource: !Sub 'arn:aws:s3:::log-storage-${AWS::AccountId}'

  CloudTrailTrail:
    Type: 'AWS::CloudTrail::Trail'
    Properties:
      TrailName: 'CloudTrail-For-Logs'
      S3BucketName: !Ref S3BucketForLogs
      S3KeyPrefix: 'cloudtrail-logs'
      IsLogging: true
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: true

  VPCFlowLogs:
    Type: 'AWS::EC2::FlowLog'
    Properties:
      LogDestinationType: s3
      LogDestination: !Sub 'arn:aws:s3:::log-storage-${AWS::AccountId}/vpc-flow-logs/${VPCId}'
      ResourceId: !Ref VPCId
      ResourceType: VPC
      TrafficType: ALL
      LogFormat: '${version} ${account-id} ${interface-id} ${srcaddr} ${dstaddr} ${srcport} ${dstport} ${protocol} ${packets} ${bytes} ${start} ${end} ${action} ${log-status}'

Outputs:
  S3BucketName:
    Description: The name of the S3 bucket where logs are stored.
    Value: !Ref S3BucketForLogs

  CloudTrailTrailArn:
    Description: The ARN of the CloudTrail Trail.
    Value: !GetAtt CloudTrailTrail.Arn

  VPCFlowLogsResourceId:
    Description: The ID of the VPC for which flow logs are captured.
    Value: !Ref VPCId
