AWSTemplateFormatVersion: '2010-09-09'
Description: Enable CloudTrail logging for management and S3 events, and configure VPC Flow Logs.

Resources:
  # S3 Bucket for CloudTrail logs
  CloudTrailS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub cloudtrail-logs-${AWS::AccountId}-${AWS::Region}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  # IAM Role for CloudTrail
  CloudTrailIAMRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudTrailPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - s3:PutObject
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                Resource: 
                  - !Sub arn:aws:s3:::${CloudTrailS3Bucket}/*
                  - !Sub arn:aws:s3:::${CloudTrailS3Bucket}

  # CloudTrail
  CloudTrail:
    Type: AWS::CloudTrail::Trail
    DependsOn: CloudTrailIAMRole
    Properties:
      TrailName: !Sub cloudtrail-${AWS::AccountId}
      S3BucketName: !Ref CloudTrailS3Bucket
      IsMultiRegionTrail: true
      IncludeGlobalServiceEvents: true
      EnableLogFileValidation: true
      IsLogging: true
      CloudWatchLogsRoleArn: !GetAtt CloudTrailIAMRole.Arn
      EventSelectors:
        - DataResources:
            - Type: AWS::S3::Object
              Values:
                - arn:aws:s3:::
          IncludeManagementEvents: true
          ReadWriteType: All

  # IAM Role for VPC Flow Logs
  VPCFlowLogsIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: vpc-flow-logs.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: VPCFlowLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  # VPC Flow Logs for all VPCs
  VPCFlowLogs:
    Type: AWS::EC2::FlowLog
    Properties:
      DeliverLogsPermissionArn: !GetAtt VPCFlowLogsIAMRole.Arn
      LogDestinationType: cloud-watch-logs
      ResourceId: !Ref 'AWS::NoValue'
      ResourceType: VPC
      TrafficType: ALL
      LogGroupName: !Sub /aws/vpc/flowlogs/${AWS::AccountId}
      MaxAggregationInterval: 60
      LogFormat: '${srcaddr} ${dstaddr} ${srcport} ${dstport} ${protocol} ${packets} ${bytes} ${action} ${log-status}'

Outputs:
  CloudTrailArn:
    Description: "CloudTrail ARN"
    Value: !Ref CloudTrail
  VPCFlowLogsGroupName:
    Description: "VPC Flow Logs Group Name"
    Value: !Sub /aws/vpc/flowlogs/${AWS::AccountId}
